### ISSUE TITLE
Program didn't find pictures that i found in other program

### ISSUE THREAD

**Issue by olejika** [m35/jpsxdec#10]
https://i.imgur.com/FnqzQCO.png

**Comment by m35** [comment]
What steps did you follow to locate that image in Tile Molester?

Attached image directly
![fnqzqco](https://user-images.githubusercontent.com/409923/41809535-3020d1b0-76a4-11e8-93b1-48549c4027b5.png)

**Comment by olejika** [comment]
I loaded .bin of Japanese version of Magical Tetris Challenge
All setting steps are on bottom of program

**Comment by olejika** [comment]
And the Palette is made by my hand

**Comment by m35** [comment]
Thank you for the details. Every PlayStation game uses their own image formats. Most of them are impossible to identify automatically. There's really no way for jPSXdec to support them all. 

Plus, the focus of jPSXdec is really on audio and video. The one image format jPSXdec does support is the only one used in most games (commonly call "Tim" images). It is very well documented and easy to automatically identify. 

For the other image formats, unfortunately you'll need to use other programs to find them.

**Comment by olejika** [comment]
If there's no way to recognize images other than .tim how PS1 and ePSXe do it?
