### ISSUE TITLE
Possible to replace any file?

### ISSUE THREAD

**Issue by gingerbeardman** [m35/jpsxdec#11]
>
> Please fill in the following information
> Note: attaching the .log files after reproducing the issue is very helpful
>

 Environment
-------------

jPSXdec version: v0-99-7_rev3397
Operating system: macOS 10.13.5 (17F77)
Java runtime environment: Version 8 Update 171

 PlayStation Game (if applicable)
----------------------------------

Name: Rally de Europe (Japan)
Region code (e.g. SLUS-1234): SLPS-02679 

 Description 
-------------

I'm trying to replace the dummy file (DUMY.STR) with a 1-byte stubbed version

it's a proper STR (has audio tracks but no video just black) but used only to pad the disc.

**Comment by m35** [comment]
jPSXdec can only replace existing frames with new frames. It can't remove frames from videos. But if you're trying to make the ISO smaller, you may be able to simply cut off those sectors from the end of the ISO.

**Comment by gingerbeardman** [comment]
OK thanks
