### ISSUE TITLE
Compatibility issues with Java 11.0.2

### ISSUE THREAD

**Issue by ZampNoxis** [m35/jpsxdec#15]
Environment
-------------

jPSXdec version: 0.99.8
Operating system: Windows 10 64-bit
Java runtime environment: 11.0.2

 PlayStation Game (if applicable)
----------------------------------

Name: 
Region code (e.g. SLUS-1234): 

 Description 
-------------

Java 11 doesn't come with a separate JRE anymore. Instead, the JRE is in the /bin folder for the JDK. Despite pointing the system environment variables to the JRE that's in the /bin folder of JDK 11.0.2 and confirming it was working by running Java commands in the command prompt, jpsxdec won't recognize Java (this has also been done with JDK 10). In 0.99.7 beta, a popup stating that a Java runtime 1.5.0 is required would show up. In 0.99.8, running the .exe does nothing. Installing any version of JRE 8 will allow jpsxdec to run. Here's what it looks like when the .jar file tries to run in the command prompt under 11.0.2:
![annotation 2019-02-14 164523](https://user-images.githubusercontent.com/30697761/52822684-059e9b00-3078-11e9-9c22-3597d4676641.png)

**Comment by m35** [comment]
Thanks for the report, and especially for trying different combinations of cases.

The `jpsxdec.exe` is generated using the very cool Launch4j. I see the latest version I used has known issues with Java 11.
https://sourceforge.net/p/launch4j/bugs/197/
https://sourceforge.net/p/launch4j/feature-requests/127/
I'll update `jpsxdec.exe` in the next release.

For that error, I see things have changed in Java 9. I've made the necessary changes locally and will be trying them out for awhile to see if anything breaks. Were you needing an untested hotfix for Java 9+ soon? The time-frame for the next jPSXdec release is unknown (but several months at a minimum).

**Comment by sallen122** [comment]
> Thanks for the report, and especially for trying different combinations of cases.
> 
> The `jpsxdec.exe` is generated using the very cool Launch4j. I see the latest version I used has known issues with Java 11.
> https://sourceforge.net/p/launch4j/bugs/197/
> https://sourceforge.net/p/launch4j/feature-requests/127/
> I'll update `jpsxdec.exe` in the next release.
> 
> For that error, I see things have changed in Java 9. I've made the necessary changes locally and will be trying them out for awhile to see if anything breaks. Were you needing an untested hotfix for Java 9+ soon? The time-frame for the next jPSXdec release is unknown (but several months at a minimum).

Nah, I'm willing to wait for the official release of the next version, but thanks anyway.

**Comment by m35** [comment]
This should be fixed in this release https://github.com/m35/jpsxdec/releases/tag/v0.99.9
