### ISSUE TITLE
Crash Team Racing XA Audio

### ISSUE THREAD

**Issue by fjay69** [m35/jpsxdec#16]
Environment
-------------

jPSXdec version: 0.99.8
Operating system: Windows 7 x64
Java runtime environment: v8 u201

 PlayStation Game
----------------------------------

Name: Crash Team Racing
Region code: SCUS-94426

 Description 
-------------

Can't convert XA audio. The program produces 4 or 8 kilobyte files.
Index.log contains lots of strings like:
[WARNING] Detected corruption in sector 0. This may affect identification and conversion.

**Comment by m35** [comment]
Try it again, then please attach the debug00.log file to this issue.

**Comment by fjay69** [comment]
[debug00.log](https://github.com/m35/jpsxdec/files/2927577/debug00.log)

**Comment by m35** [comment]
Thanks. There's definitely something wrong with your file. It is missing the raw sector headers required to decode XA audio. If the file had the raw sector headers, it would be about 7940352 bytes in size. The method you used to extract the file S20.XA did not include the raw sector headers.

One way to extract the file with the raw sector headers is to open the game's full `.BIN` disc image in jPSXdec and use it to extract the file. Then it will contain the required sector headers.

**Comment by fjay69** [comment]
Indeed. After scanning full disk image all XA audios are playing fine now. Thanks.
