### ISSUE TITLE
.EXE not running

### ISSUE THREAD

**Issue by 0Shift** [m35/jpsxdec#19]
Environment
-------------

jPSXdec version: v0.99.8
Operating system: Windows 10 64 bit 
Java runtime environment: 11.0.2

 PlayStation Game (if applicable)
----------------------------------

Name: 
Region code (e.g. SLUS-1234): 

 Description 
-------------

application isn't starting, tried running as admin but still no response

**Comment by m35** [comment]
Unfortunately jPSXdec isn't working right with any version of Java past version 8. This other issue has more details https://github.com/m35/jpsxdec/issues/15

This will be fixed in the next release. Until then, if you can use Java 8 it will work.

**Comment by m35** [comment]
This should be fixed in this release https://github.com/m35/jpsxdec/releases/tag/v0.99.9
