### ISSUE TITLE
v0-99-7_rev3397 Final Fantasy IX  (Disc 1) Opening movie no sound

### ISSUE THREAD

**Issue by blind227** [m35/jpsxdec#2]
Environment
-------------

jPSXdec version: v0-99-7_rev3397
Operating system: Win 10 x64
Java runtime environment: jre1.8.0_111

 PlayStation Game (if applicable)
----------------------------------

Name: 
Region code (e.g. SLUS-1234): 
SLPS_020.00  Final Fantasy IX  (Disc 1)

 Description 
-------------
FMVD001.STR  Opening movie  No sound  
other movies sound ok

**Comment by m35** [comment]
Thank you for reporting this. Unfortunately that FF9 video FMVD001.STR doesn't use recorded XA audio for the sound. Instead, the game generates instrumental music separate from the movie (often referred to as "SEQ"). That kind of audio cannot be found by jPSXdec. 

If you're interested in more details, you can check this blog post http://jpsxdec.blogspot.com/2016/07/spu-and-hd-conversion.html
