### ISSUE TITLE
java.lang.RuntimeException at jpsxdec.modules.roadrash.RoadRashPacket$MDEC.readPacket(RoadRashPacket.java:351)

### ISSUE THREAD

**Issue by yoosefi** [m35/jpsxdec#21]
Tried to open PlayStation Magazine Demo Disc 14,

Debug log attached.

The disc is *ahem* "only available for streaming".

https://archive.org/details/psx_opm14

You should (not) open the dev console and watch the network activity for a MAME `chd` file, nor should you use `mame-tools` to convert it to a `bin`

This couldn't be a `chdman` issue could it? I wouldn't know, I have (not) used it plenty of times on other discs before running into this issue.

[debug00.log](https://github.com/m35/jpsxdec/files/3495094/debug00.log)

**Comment by m35** [comment]
Seems like jPSXdec found data that looks like a Road Rash FMV, but the video has unsupported dimensions. But jPSXdec shouldn't blow up in any case, so this would be a bug.
Do you know what FMVs are available to play from the game?

**Comment by m35** [comment]
This should be fixed in https://github.com/m35/jpsxdec/releases/tag/v1.00
