### ISSUE TITLE
PS2 game support in future?

### ISSUE THREAD

**Issue by gledson999** [m35/jpsxdec#22]
Hi, this tool is incredible, would be interesting have future support for PS2 game formats like PSS (PlayStation Stream), SFD (CRI Softdec Video), BIK (BIK Video Container), MPC (Electronic Arts), VP6 (Electronic Arts)

**Comment by m35** [comment]
Thank you :)
Unfortunately PS2 support would be impossible in jPSXdec. It would require a whole new program designed from the ground up to support its more advanced media formats.
