### ISSUE TITLE
Exception when replacing audio

### ISSUE THREAD

**Issue by jubei85** [m35/jpsxdec#23]
Environment
-------------

jPSXdec version: jpsxdec_v1-00_rev3921
[debug10.log](https://github.com/m35/jpsxdec/files/3756230/debug10.log)

Operating system: Windows 10 pro (x64)
Java runtime environment: 1.8.0_231-b11

 PlayStation Game (if applicable)
----------------------------------

Name: Silent Hill 1
Region code: 

 Description 
-------------
Replaced the audio:
java -jar jpsxdec.jar -x 1.idx -i 1232 -replacexa "HILL[12].wav"
java -jar jpsxdec.jar -x 1.idx -i 1232 -replacexa "HILL[12].au" etc..
Everything works in the old version (jpsxdec_v0-99-7_rev3397)

An error appears in the current version:
`Using source file D:\PSX\ut\jpsxdec\rom\Silent Hill (v1.1).bin
1988 items loaded.
ERROR: java.lang.IllegalStateException (IllegalStateException)
D:\PSX\ut\jpsxdec>`

**Comment by m35** [comment]
Thank you for reporting this. Confirmed it is a bug. It was broken when rearranging the replacing logic in v0.99.8. v0.99.7 works perfectly fine at replacing audio if you want to use it. The audio will be replaced in the same way v0.99.8 would if it didn't have this bug.

**Comment by jubei85** [comment]
Thank you!

**Comment by m35** [comment]
This is a good issue to track the bug. I'll close it when it is fixed, thanks 🙂  👍

**Comment by m35** [comment]
Fixed https://github.com/m35/jpsxdec/releases/tag/v1.01
