### ISSUE TITLE
Some WVE files still not detected if scanned from a .bin image.

### ISSUE THREAD

**Issue by BloodRaynare** [m35/jpsxdec#25]
Environment
-------------

jPSXdec version: jpsxdec_v1-00_rev3921
Operating system: Windows 8.1 x64
Java runtime environment: build 1.8.0_231-b11

 PlayStation Game (if applicable)
----------------------------------

Name: NASCAR Rumble
Region code (e.g. SLUS-1234): SLUS-01068 

 Description 
-------------

What were you doing?:
I tried to scan the WVE files inside of the image.

What happened?:
While almost of them are detected, there's some of the files that aren't detected. 
![NotDetected](https://user-images.githubusercontent.com/46045141/70685721-cca57600-1cdc-11ea-8f5e-7ab747373b94.png)
However, if I open the WVE directly (By extracting it from the image or mount the bin with virtual drive software), it works though
![OpenedManually](https://user-images.githubusercontent.com/46045141/70685754-e34bcd00-1cdc-11ea-9957-22271a5d136c.png)

What was or was not supposed to happen?:
All of the WVE files inside of the image should be detected.

And here I provided the debug.log as well if it helps
[debug00.log](https://github.com/m35/jpsxdec/files/3954012/debug00.log)

**Comment by m35** [comment]
Good catch, thanks for the report. The detection logic has a bug. You found a good workaround to extract the file and then open it with jPSXdec.

**Comment by BloodRaynare** [comment]
Oh yes, I also want to add something.
Archived files (like Madden's FMVIDEO.DAT) might have some of the WVE stream undetectable as well even when directly opened.

**Comment by m35** [comment]
Can you find a specific example of a video that isn't being detected?

**Comment by BloodRaynare** [comment]
Do you want me to send a sample file?

**Comment by m35** [comment]
For example, you mentioned there may be WVE videos in Madden 99 FMVIDEO.DAT that are not detected. Can you identify a video in the game that isn't being found by jPSXdec?

**Comment by BloodRaynare** [comment]
Okay, hold on. I'll try to split the WVE video inside the FMVIDEO.DAT and see which video that didn't detected by jpsxdec. I'll report back when I find out.

**Comment by BloodRaynare** [comment]
Okay, here'a a small list I gathered (With their offsets and sizes) from my testing with Madden 99 and 2000:

[notdetectedbyjpsxdec.txt](https://github.com/m35/jpsxdec/files/3958774/notdetectedbyjpsxdec.txt)

**Comment by m35** [comment]
Give this a try https://github.com/m35/jpsxdec/releases/tag/v1.02

**Comment by BloodRaynare** [comment]
Almost there.....
All of the WVE videos on NASCAR Rumble & Madden 99 are successfully detected. And I think it also fixed one of the videos on Road Rash Jailbreak that was undetected on current latest release as well. However, Madden 2000 still missing one of the videos though. And that's on the offset 08393800 of FMVIDEO.DAT (jpsxdec only detects 35 of 36 of the video files and that video supposed to be after the number 21).

And, also
When I tried to scan the NASCAR Thunder 2002 bin images and it's two next iterations (2003 and 2004), jpsxdec give this output on index.log

> jPSXdec: PSX media decoder (non-commercial) v1.02 (beta)
> Windows 8.1 6.3
> Java 1.8.0_231
> 14 Des 19 11:34:23
> [INFO] Indexing Filename:F:\Gaming Stuffs\ISOs\Toshiba HDD Backup\PS1\NASCAR Thunder 2002 (USA)\NASCAR Thunder 2002 (USA).bin|Sector size:2352|Sector count:95473|First sector offset:0
> [SEVERE] EA video data corruption
> [INFO] Time: 4 sec

But when I play that problematic WVEs by extracting the DATA.BIN inside of the image, jpsxdec scanned and detected it just fine, still with the warning though.

> jPSXdec: PSX media decoder (non-commercial) v1.02 (beta)
> Windows 8.1 6.3
> Java 1.8.0_231
> 14 Des 19 11:38:33
> [INFO] Indexing Filename:F:\Gaming Stuffs\Data Mining & Mod Stuff\NASCAR2K2PSX\DATA\DATA_014.vlc|Sector size:2048|Sector count:7687|First sector offset:0
> [WARNING] File does not have raw sector headers -- audio may not be detected.
> [INFO] Time: 1,32 sec

**Comment by m35** [comment]
Wow thanks for keeping me on my toes :)
I reworked the detection logic. Can you try this one?
[EA_test_1.zip](https://github.com/m35/jpsxdec/files/3964221/EA_test_1.zip)

Don't worry about this warning, it only applies to normal PS1 videos. EA videos don't need raw sector headers.
 > [WARNING] File does not have raw sector headers -- audio may not be detected.

**Comment by BloodRaynare** [comment]
It's all perfect now :) All of the videos detected without a hitch.

**Comment by m35** [comment]
I can add all the games you tested to the supported `PSXListOFGames.txt` if you're willing to share.

**Comment by BloodRaynare** [comment]
Okay, here's a list of the games I tested with:

- Supercross 2000
- EA Sports Supercross (aka Supercross 2001)
- NASCAR 98 (and it's Collectors Edition)
- NASCAR 99 (and it's Legacy version)
- NASCAR 2000
- NASCAR 2001
- NASCAR Thunder 2002
- NASCAR Thunder 2003
- NASCAR Thunder 2004
- NASCAR Rumble
- Madden NFL 99
- Madden NFL 2000
(All of Madden after this one maybe using this format as well)
- Road Rash 3D
- Road Rash Jailbreak
- Future Cop L.A.P.D.

**Comment by m35** [comment]
Awesome! Thanks for the game id :D
Here's the official release
https://github.com/m35/jpsxdec/releases/tag/v1.03

**Comment by BloodRaynare** [comment]
Late to reply, but thanks. I think it can be closed now.
