### ISSUE TITLE
Any plans to add modern video formats/codecs (if possible)? + Rakugaki Showtime report

### ISSUE THREAD

**Issue by Tenome** [m35/jpsxdec#26]
Your tool is incredibly useful, for which I thank you. I was just wondering since AVI is an old format. Or maybe there's reason it has to be AVI? I have no idea.

Also, you can check off Rakugaki Showtime as [!] if you still update your Testing list. Everything extracted and converted just fine, except for the sound effects (you can extract those with PSound). I'm not sure which file the SFX were stored in. Maybe ARA.bin? In any case, JPSXDec didn't find them.

https://puu.sh/Faeb8/ae050e7bc4.png

Index:
https://pastebin.com/2mDfjZcT

**Comment by m35** [comment]
Thanks! :)

I've looked pretty closely into alternative formats, namely .mov .mkv and .mp4. I was really hoping I could use .mov and .mkv because they support variable frame rates. Unfortunately none allow for uncompressed video, so we're stuck with .avi.

**Comment by Tenome** [comment]
I actually did not know that AVI was uncompressed (I presume each frame is a TIF?). No worries then, thanks.

**Comment by m35** [comment]
Technically AVI is just a container and can contain audio and video using different formats/codecs. The uncompressed video format it basically just a sequence of .bmp image. The compressed video is a sequence of .jpg images. For audio in the AVI, it always uses .wav format.
