### ISSUE TITLE
can you do a program to can ripp models of racing pex games or models?? like chocobo racing?

### ISSUE THREAD

**Issue by Dan92xD** [m35/jpsxdec#27]
Environment
-------------

jPSXdec version: 
Operating system: 
Java runtime environment : 

 PlayStation Game (if applicable)
----------------------------------

Name: 
Region code (e.g. SLUS-1234): 

 Description 
-------------

What were you doing?:

What happened?:

What was or was not supposed to happen?:

**Comment by m35** [comment]
Will not be developing a model ripping program.
