### ISSUE TITLE
Error：execute jpsxdec.exe then notice:Could not find the main class:jpsxdec.Main

### ISSUE THREAD

**Issue by spooky18** [m35/jpsxdec#28]
JDK Version：1.6.30/1.6.45
OS：XP SP3/Win 7 SP1
jpsxdec：v1.00 rev3921 (7 Sept 2019)
Error：execute jpsxdec.exe then notice:Could not find the main class:jpsxdec.Main.   Program will exit

**Comment by m35** [comment]
This system worked for me without issues.
```
jPSXdec: PSX media decoder (non-commercial) v1.00
Windows XP 5.1
Java 1.6.0_45
```
Could you delete the `jpsxdec.ini` file (if it exists) and run
`java -jar jpsxdec.jar`
And then attach the `debug00.log` file?

**Comment by vitacell** [comment]
I had same problem but in GNU/Linux. I ran "java jpsxdec.jar", and had same error. Now I run "java -jar jpsxdec.jar" and it works. So, I think that you have to add "-jar" parameter to somewhere.

**Comment by m35** [comment]
Thanks @vitacell for your comment. Maybe it will help someone.

Closing this old issue. If this is sill a problem, feel free to add a comment or create a new issue.
