### ISSUE TITLE
TIM image not found in file

### ISSUE THREAD

**Issue by gmarty** [m35/jpsxdec#29]
Environment
-------------

jPSXdec version: v1.00
Operating system: MacOS
Java runtime environment : 
java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)

 PlayStation Game (if applicable)
----------------------------------

Name: Matsumoto Leiji 999 \~Story of Galaxy Express\~
Region code (e.g. SLUS-1234): SLPS-03220 & SLPS-03221

 Description 
-------------

What were you doing?:
Extracting images from some .DB2 files.

What happened?:
I managed to reverse engineering the way the assets are concatenated together into .BD2 archives.
On one file (DAT/BSTAGE.BD2), there is an image at the beginning that is not found by jpsxdec.

I can give you more details like the offset of where the TIM file starts and its length. I suspect this image to have many palettes.

All the other images were able to be extracted as expected by jpsxdec.

What was or was not supposed to happen?:
This image should be extracted like the other ones.

**Comment by m35** [comment]
Hi, yes the Tim start and length would definitely be helpful.

**Comment by gmarty** [comment]
Here are the details:
```
file: DAT/BSTAGE.BD2
offset: 19104,
size: 32360,
```

When decrypted with another tool, this image is 252 x 253 and here's what it looks like with the 1st palette (it's a texture for one of the levels):
![1](https://user-images.githubusercontent.com/333865/84871244-33cf2900-b078-11ea-9e96-8a407fba0466.png)

**Comment by m35** [comment]
Hopefully this is fixed in today's release. Let me know if you experience any more issues.

https://github.com/m35/jpsxdec/releases/tag/v1.04
