### ISSUE TITLE
"-replacexa" command does not work

### ISSUE THREAD

**Issue by ViToTiV** [m35/jpsxdec#30]
Environment
-------------

jPSXdec version: v1-03_rev3953
Operating system: Win10 x64
Java(TM) SE Runtime Environment (build 1.8.0_251-b08)

 PlayStation Game (if applicable)
----------------------------------

Name: Syphon Filter 2 (and any others)
Region code: SCES-02288

 Description 
-------------

Starting from version "v0.99.8 rev3788" to last one, the "-replacexa" command does not work. Progress is going, but a new file is not inserted.
Please fix it, your tool is very useful.

**Comment by m35** [comment]
This should be fixed in today's release. Let me know if you experience any more issues.

https://github.com/m35/jpsxdec/releases/tag/v1.04
