### ISSUE TITLE
Cannot extract the graphics from 40 Winks

### ISSUE THREAD

**Issue by inferno986return** [m35/jpsxdec#31]
Environment
-------------

jPSXdec version: 1.00
Operating system:  Windows 10 Pro (64-Bit)
Java runtime environment :  Version 8 Update 271 (build 1.8.0_271-b09)

 PlayStation Game (if applicable)
----------------------------------

Name:  40 Winks
Region code (e.g. SLUS-1234):  SLUS-00874

 Description 
![Annotation 2020-10-24 184144](https://user-images.githubusercontent.com/1838420/97095978-d79b9780-165d-11eb-82b5-4c6b0dfc551b.png)

-------------

What were you doing?: Extracting the 40 WInks .bin file

What happened?: Extraction of the game soundtrack (in .wav form) and the game's FMV assets were successful. But not the OVERLAY.BIN and GFXFILE.BIN.

What was or was not supposed to happen?: I was hoping that those two .bin files could be extracted, however the tool says there are no raw headers and no files are within them.

**Comment by m35** [comment]
Unfortunately if the game doesn't use the standard Tim image format, jPSXdec won't be able to detect any graphics. A lot of games use their own unique formats that jPSXdec won't understand.
