### ISSUE TITLE
Can't extract intro video from Ridge Racer Type 4 [PAL]

### ISSUE THREAD

**Issue by nbmrjuhneibkr** [m35/jpsxdec#33]
Environment
-------------

jPSXdec version: v1.00 rev3921 and v1.04 rev3987
Operating system: Windows 8.1 x64
Java runtime environment: 1.8.0_271-b09

 PlayStation Game (if applicable)
----------------------------------

Name: R4: Ridge Racer Type 4
Region code: SCES-01706

 Description 
-------------

jPSXdec detects audio track from the R4 intro, but without video. This only happens with the PAL version, NTSC intro (SLUS-00797) can be detected with no issues. The end credits video is not affected by this issue.

**Comment by m35** [comment]
New release should support the video. Comment here if you have any issues.
https://github.com/m35/jpsxdec/releases/tag/v1.05
