### ISSUE TITLE
How to replace modified video w audio in Chrono Cross?

### ISSUE THREAD

**Issue by saifhashmi210** [m35/jpsxdec#35]
Environment
-------------

jPSXdec version: v1-04_rev3987
Operating system: Windows 10 x64 Home
Java runtime environment : openjdk version "1.8.0_282"

 PlayStation Game (if applicable)
----------------------------------

Name: Chrono Cross
Region code (e.g. SLUS-1234): SLUS-01041

 Description 
-------------

Hi, I found jpsxdec to be really helpful at being able to view/extract/convert videos from Chrono Cross but I'm looking to replace them with my own videos. Unfortunately Chrono Cross' cd contents use a different lookup table and the video/audio files themselves dont follow the standard STR/XA format. The replace-frames work with the last "Unnamed" video file but the replace-xa doesnt recognize the audio stream as an XA format. I wasn't able to re-inject modified .STR files using the same sector (xtractor.net) either as It boots to a black screen, probably because the audio/video sector doesnt match up to the documentation.

![pic_regulardisc](https://user-images.githubusercontent.com/56486618/111055296-19c14c00-843a-11eb-9ffe-859a8770f253.png)

Any ideas or help would be appreciated. Thank you.

**Comment by m35** [comment]
Sorry, audio from SquareSoft games is the one audio format that jPSXdec currently can't replace. I'll add the feature in the next release.

**Comment by m35** [comment]
New release should include the change. Comment here if you have any issues.
https://github.com/m35/jpsxdec/releases/tag/v1.05

**Comment by saifhashmi210** [comment]
Wow, didn't expect a new build so quickly.
-replaceaudio worked perfectly. I just let jpsxdec convert the .wav/.aif for me and as long as the exact sample length was the same (thank you Audacity), it worked fine. Thank you so much, Im glad I didnt have to go in and hex edit the whole sectors myself!

**Comment by m35** [comment]
Holy cow thank you for the tip! 😮
