### ISSUE TITLE
Digimon World 2003 Missing Textures

### ISSUE THREAD

**Issue by lunarain0** [m35/jpsxdec#39]
Environment
-------------

jPSXdec version: 1.00rev3921
Operating system: Windows 10
Java runtime environment : 1.8.0_281

 PlayStation Game (if applicable)
----------------------------------

Name: Digimon World 2003
Region code (e.g. SLUS-1234): SLES-03936

 Description 
-------------

What were you doing?: Trying to extract the field texture files.

What happened?: Many textures are missing, as an example I have included a diagram of the textures that were extracted for the Asuka city area compared to a stitched screenshot of the game. It seems there must be something different about the way these textures are stored as PsPicture couldn't find them either.

What was or was not supposed to happen?: Ideally all the textures would be found.

![image](https://user-images.githubusercontent.com/25795926/133516795-6dd310b1-7902-4a17-b0ea-20a2b7238d6d.png)

**Comment by m35** [comment]
That is an absolutely stunning diagram. 
Can you try v1.05? The Tim detection logic was improved and should detect more.
https://github.com/m35/jpsxdec/releases/tag/v1.05

**Comment by lunarain0** [comment]
Unfortunately the newer version didn't detect any more images. I spent a lot of time last night looking at the VRAM in some save states and from what I can tell from searching with a hex editor, the missing image files for each map are in the same bin files as the rest, but they must be stored in some other way because no software has been able to find them and I couldn't locate any other incomplete TIM headers when I searched for them myself.

**Comment by m35** [comment]
Nice investigation. Can you share a few examples of an LBA + offset where an image starts that isn't being detected? Or is it 1 like image per .bin file?

**Comment by lunarain0** [comment]
I made a diagram to try and show my investigation. Each ___PACK.BIN seems to contain the textures for a field in the game. However only a small percentage of those textures seem to be stored in the normal way. 

![image](https://user-images.githubusercontent.com/25795926/133905250-d0985f95-5336-49f6-b841-fc52b4d903b7.png)

**Comment by m35** [comment]
Thank you for the details. I've seen Tim-like data that is missing a standard Tim header in other games. It's odd in this case that they mixed standard Tim images with non-standard ones.

You've done some great investigation. I would have done exactly the same thing to find what was going on, so I don't think there's anything more I can add. Unfortunately without a standard header there's not much jPSXdec can do to know if the data is a Tim image or not. And even if these images do have some kind of header that could be identified, it may just be specific to this one game. Special handling for unique Tim images isn't something I plan to add to jPSXdec (I'm focused primarily on videos and audio).

But thank you for taking time to report this. It helps me be more aware of the kind of unique things developers did to store their data.

**Comment by lunarain0** [comment]
Thanks for your time, I really appreciate what you're doing with the app regardless.
