### ISSUE TITLE
Andretti Racing - Sector scanning fails with error message

### ISSUE THREAD

**Issue by BloodRaynare** [m35/jpsxdec#40]
Environment
-------------

jPSXdec version: jpsxdec_v1-05-beta
Operating system: Windows 8.1 Pro x64
Java runtime environment :  openjdk version "11.0.11" 2021-04-20

 PlayStation Game (if applicable)
----------------------------------

Name: Andretti Racing
Region code (e.g. SLUS-1234): SLUS-00264

 Description 
-------------

What were you doing?:
I was trying to analyze the contents inside the Track 1 (which is the game's main track for the data except the BGMs which uses CD audio)

What happened?:
Upon reaching sector 45979, jPSXdec threw this error message and thus abort the scanning process:
![AndrettiError](https://user-images.githubusercontent.com/46045141/134458218-373a4fe3-ba00-4054-ae0b-571b8195d6e6.png)
This is probably related to the WVE format support.

What was or was not supposed to happen?:
jPSXdec should able to scan all of the datas, or at least treat the unrecognizable data as a generic non-stream file.

Also, here's both of the log files
[debug00.log](https://github.com/m35/jpsxdec/files/7215139/debug00.log)
[index.log](https://github.com/m35/jpsxdec/files/7215140/index.log)

**Comment by m35** [comment]
Thank you for taking time to report this. It's indeed a bug and will be fixed in the next release.

**Comment by m35** [comment]
This has been fixed in the latest release. Feel free to reopen this issue if you find any other issues.
https://github.com/m35/jpsxdec/releases/tag/v1.06

**Comment by m35** [comment]
Also just FYI it looks like Electronic Arts was perhaps the most creative with unique FMV formats. Andretti Racing uses the same format found in Crusader: No Remorse, along with Soviet Strike and Battle Stations. This is a different format than the one used in issue #25. Not only that, there is yet another unique format that has been uncovered in other EA games that will be added in future releases.
