### ISSUE TITLE
No Commandline Argument for skipping audio from video files

### ISSUE THREAD

**Issue by Meerkov** [m35/jpsxdec#42]
I noticed that the UI allows you to skip audio files that come from video files. But the command line arguments don't seem to have that option. It would be nice to have.

**Comment by m35** [comment]
So I'm clear, you mean when saving all audio? 
```
java -jar jpsxdec.jar -a audio ...
```

**Comment by Meerkov** [comment]
Yes, I currently am trying running both
`java -jar jpsxdec.jar -a audio`
and 
`java -jar jpsxdec.jar -a video`
In the UI I can skip audio from video files, but command line doesn't seem to have the option

**Comment by m35** [comment]
Thanks for clarifying. You're right, I missed adding that option to the command-line. I'll add a new command-line option in the next release `-skipvid` that will skip any audio that is associated with a video, like you can do in the UI.
```
java -jar jpsxdec.jar -a audio -skipvid
```

**Comment by m35** [comment]
Reflecting on this more, I think it makes more sense to, by default, ignore audio streams that are associated with a video stream. Then add a command line argument to override that. Best I could come up with is `-vidaud`

**Comment by m35** [comment]
This has been added in the latest release. Feel free to reopen this issue if you find any other issues.
https://github.com/m35/jpsxdec/releases/tag/v1.06
