### ISSUE TITLE
Zooboomafoo - Leapin' Lemurs! detects 18000 sound effects

### ISSUE THREAD

**Issue by Meerkov** [m35/jpsxdec#49]
1) Try to extract audio from Zooboomafoo - Leapin' Lemurs!
2) Notice that about 18000 .wav files are created
3) Only the first ~500 look valid, and everything after that is exactly 4KB in size, and seem to be garbage data.

Seems like something went wrong with the index?

jspx v1.00

**Comment by Meerkov** [comment]
I sometimes see similar issues in other games, but I'm assuming it's all the same root cause.

**Comment by m35** [comment]
For all these games with audio issues, i.e. too many small clips, can you try using v1.06? The audio detection was improved since 1.00. 
#51 #52

You'll definitely want to use 1.06 in general. The only issue keeping it from a non-beta release is the translations haven't been updated since v1.00.

**Comment by Meerkov** [comment]
Thanks! Looks like 1.06 fixed this issue.
