### ISSUE TITLE
Newest JRE prevents the embed Media Player to work.

### ISSUE THREAD

**Issue by alebersol** [m35/jpsxdec#5]
>
> Please fill in the following information
> Note: attaching the .log files after reproducing the issue is very helpful
>

 Environment
-------------

jPSXdec version: 0.99.7
Operating system: Linux localhost 4.6.3-pclos1 #1 SMP Fri Jun 24 15:24:36 CDT 2016 x86_64 x86_64 x86_64 GNU/Linux
Java runtime environment: 1.8.0_131

 PlayStation Game (if applicable)
----------------------------------

Name: 
Region code (e.g. SLUS-1234): 

 Description 
-------------

What happened?:
Media player doesn't work. Does not play audio nor videos
What was supposed to happen?: The media player should play audio and videos 

What were you doing?:Testing the new version (0.99.7).  I guess it's a problem of the newest JRE, might have broke something.

**Comment by m35** [comment]
Can you check this new release?  https://github.com/m35/jpsxdec/releases/tag/v0.99.9
The media player has been revamped.

**Comment by alebersol** [comment]
Ok Mr. Sabin,

Gonna take a look,

Thanks for the letting me know.

Regards,



Em sáb, 10 de ago de 2019 às 04:23, Michael Sabin <notifications@github.com>
escreveu:

**Comment by Meerkov** [comment]
Running JRE 8u291 , and jpsxdec 1.00 I am able to use the video and audio preview feature without issues.

I think this can be closed now.

**Comment by m35** [comment]
Thanks, yeah this has been open long enough.
