### ISSUE TITLE
"disc image does not contain raw header - audio may not be detected" ??

### ISSUE THREAD

**Issue by placeboyue** [m35/jpsxdec#54]
Environment
-------------
jPSXdec version: literally tried a dozen of them, but im currently using 0.99.6 because someone else managed to rip the sounds i want with it, yet i cannot.
Operating system:  W10
Java runtime environment :   1.8.0_201

 PlayStation Game (if applicable)
----------------------------------
Name:  Digimon World 2
Region code (e.g. SLUS-1234):  SLUS-01193

 Description 
-------------
What were you doing?: opening XAP files

What happened?: "disc image does not contain raw header - audio may not be detected", no audios detected

What was or was not supposed to happen?: someone else did the exact same thing and found the audios im looking for. The only difference i find is that when he opens it, it says "BIN/CUE format (2000 bytes format blahblah)" and i get "iso format" and there's no way to change that. Perhaps that's the issue? what's going on here?

I tried the latest version, and much older ones, none worked for me. I haven't tried a BIN version of the game yet to see if it works. But if it did, this still means that the tool fails when dealing with ISO games? It does encounter some audios, but not all.

**Comment by m35** [comment]
Can you try using the BIN version of the game? That should resolve the issue.

A lot of audio data requires the raw sector headers that are only available when you rip a disc as BIN/CUE (2352 bytes/sector). Without the raw headers, it's simply impossible to identify or decode the audio. 

But not all game data require the raw headers. Some data can be safely extracted from .iso (2048 bytes/sector) files. But that's on a case-by-case basis. So it's strongly recommended you make a BIN/CUE rip of the entire disc and open that with jPSXdec. That way you're sure to get everything the game has to offer.
