### ISSUE TITLE
replacetim command not work

### ISSUE THREAD

**Issue by 2601677867** [m35/jpsxdec#55]
Environment
-------------

jPSXdec version: v1.00
Operating system:  Windows 10 LTSC
Java runtime environment : 1.8.0_311

 PlayStation Game (if applicable)
----------------------------------

Name: Biohazard - Gun Survivor
Region code (e.g. SLUS-1234): SLPS-02553

 Description 
-------------

What were you doing?: try to replace the tim file

What happened?: Nothing happens after using replacetim command Scanned the game disc file again, nothing changed in the TIM file

What was or was not supposed to happen?: TIM file should be replaced

i use this command

java -jar jpsxdec.jar -f "D:\PSX\Biohazard - Gun Survivor (Japan)\Biohazard - Gun Survivor (Japan).bin" -x re.idx -replacetim "OPTTIM.BIN[5].tim"

**Comment by m35** [comment]
It looks like the issue is with the command you're using. Make sure to include the `-i <index number>` option to say which item you're replacing. For example, if the index number is `55` use

```
java -jar jpsxdec.jar -f "D:\PSX\Biohazard - Gun Survivor (Japan)\Biohazard - Gun Survivor (Japan).bin" -x re.idx -i 55 -replacetim "OPTTIM.BIN[5].tim"
```

**Comment by 2601677867** [comment]
It's work ! Thank you very much ！

But I get an error message, I don't understand what does xy(704,256) mean in the error message?

`New TIM format "320x240 8bpp xy(1, 1) WWidth:160 Len:76812 CLUT[256x1 xy(2, 2) Len:524]" does not match existing TIM format "320x240 8bpp xy(704, 256) WWidth:160 Len:76812 CLUT[256x1 xy(320, 507) Len:524]"`

**Comment by m35** [comment]
`xy(704,256)` are the coordinates where the TIM images should be copied into the VRAM, which is very important so the game knows where to access the image. The coordinates (2, 2) usually are in the top left corner of the screen and would be overwritten immediately. Are you sure you want to use those coordinates?

**Comment by 2601677867** [comment]
So is there any way to keep the xy() value of the modified TIM file consistent with the xy() value of the original TIM file?

**Comment by m35** [comment]
Unfortunately jPSXdec doesn't have an option to change those values because I hoped that any tool that lets you edit TIM images would let you set those values (or at least keep them the same). What tool did you use to edit or make the TIM image?

**Comment by 2601677867** [comment]
I use TIM Viewer to convert bmp images to tim

[TIM Viewer](https://www.romhacking.net/utilities/486/)

**Comment by m35** [comment]
Hmm it's disappointing it doesn't give that option. I did a bit of searching and found img2tim. It's a command-line tool, but appears to have the option to set those values. Maybe it can help?
https://github.com/ArthCarvalho/img2tim/blob/master/img2tim.txt#L27

**Comment by 2601677867** [comment]
replace success Thank you very much !
