### ISSUE TITLE
Missing Manual

### ISSUE THREAD

**Issue by Meerkov** [m35/jpsxdec#56]
I can't find the manual anywhere. :)

**Comment by Meerkov** [comment]
This was the only copy I was able to find that isn't behind a paywall. What happened to the original?
https://www.flipsnack.com/isra3bdel/jpsxdec-manual.html

**Comment by m35** [comment]
The Open/LibreOffice version is in the repo
https://github.com/m35/jpsxdec/blob/readme/jpsxdec/doc/jPSXdec-manual.odt
The pdf version is built under the /doc/ directory in any release.
