### ISSUE TITLE
Silverload - FMVs not found

### ISSUE THREAD

**Issue by Meerkov** [m35/jpsxdec#58]
The game Silverload has FMVs but they don't extract.

**Comment by m35** [comment]
If it's not too much trouble, could you open and index the disc, then attach the debug00.log file here?

**Comment by Meerkov** [comment]
Actually, upon double checking, it looks like it was a different tool in my chain which was failing. I was able to get them out when I tried again.

**Comment by m35** [comment]
@Meerkov if it's not too much trouble, could you email me at jpsxdec@gmail.com ? I would like to get your thoughts on some of the changes in the upcoming release.
