### ISSUE TITLE
Lightspan games not on the master game list

### ISSUE THREAD

**Issue by Meerkov** [m35/jpsxdec#62]
e.g. "Head to Toe" is not included in the master game list file. It probably doesn't matter, but this list is the best one I've found on the net. Might be nice to add those ~100 or so games.

**Comment by m35** [comment]
Thanks for noticing they weren't on the list. 
Unfortunately the list hasn't really helped and may be causing more confusion for people. jPSXdec has been tested enough at this point that I think it's more helpful to identify games with issues than games that work. I went ahead and removed PSXListOFGames.txt.
And again thank you so much for reporting issues you've come across. Maybe some day I'll have time to work on them 😅
