### ISSUE TITLE
Can't extract audio/music from "Magical Tetris Challenge"

### ISSUE THREAD

**Issue by EpicLPer** [m35/jpsxdec#7]
Environment
-------------

jPSXdec version: 0.99.7 beta
Operating system: Windows 10 x64 1709 German
Java runtime environment: Java 8 Update 151

 PlayStation Game (if applicable)
----------------------------------

Name: Magical Tetris Challenge
Region code (e.g. SLUS-1234): SCES-02154

 Description 
-------------

What happened?: Intro Video can be exported (tho without sound), however when trying to open the XA-files it'll result in almost 2000 WAV files all of the size of around 8KB and unplayable. Game was playable so the files don't seem to be corrupt despite the log saying otherwise, plus I got the Sound FX extracted via PSound, I've worked with a downloaded IMG file which I extracted via TUGZip.
[debug0.zip](https://github.com/m35/jpsxdec/files/1650283/debug0.zip)

What was supposed to happen?: Exported Music.

What were you doing?: Trying to export the music.

**Comment by m35** [comment]
The debug0.log shows it was trying to identify what type the `DM1E.BIN` file was (it logs a lot of errors during the identification process that aren't actually errors). That is a very small file that doesn't contain any XA audio, so nothing would be detected by jPSXdec.

I don't know why jPSXdec had trouble detecting XA audio. I tested my copy of the game with v0.99.7 and it properly detected the STR video and the XA audio.

![image](https://user-images.githubusercontent.com/409923/71327743-86fd6000-24c9-11ea-9a83-a4630ed774f8.png)

**Comment by EpicLPer** [comment]
> The debug0.log shows it was trying to identify what type the `DM1E.BIN` file was (it logs a lot of errors during the identification process that aren't actually errors). That is a very small file that doesn't contain any XA audio, so nothing would be detected by jPSXdec.
> 
> I don't know why jPSXdec had trouble detecting XA audio. I tested my copy of the game with v0.99.7 and it properly detected the STR video and the XA audio.
> 
> ![image](https://user-images.githubusercontent.com/409923/71327743-86fd6000-24c9-11ea-9a83-a4630ed774f8.png)

I've tried it with the latest version and all of the sudden it works... Not sure how you fixed it but you did haha :)
In the end I ended up extracting it directly from the original disc and having to set up XP due to it being the last NT based OS which was able to directly access the CD drive apparently without any drivers in between, then I archived it on YouTube since no one seemed to care about that music. Due to scratches in the disc I had to do it multiple times to get all dem Bits correctly off ;)

Yup, that would've made it a lot less time consuming back then :D
