### ISSUE TITLE
About replacing spoken dialog in Silent Hill

### ISSUE THREAD

**Issue by AlbertWesker86** [m35/jpsxdec#71]
Environment
-------------

jPSXdec version: v1.00
Operating system: Windows 11 x64 Home
Java runtime environment : openjdk version "1.8.0_282"

 PlayStation Game (if applicable)
----------------------------------

Name: Silent Hill
Region code (e.g. SLUS-1234): SLES-01514

 Description 
-------------

My goal is to replace all spoken dialog with a new fandub. I know how to extract the audio files, but I'm clueless about if is it possible to replace them in any way. Your work with this tool is incredible!! I'll appreciate any insight on the matter,

thank you for your time!!

**Comment by m35** [comment]
jPSXdec does give you the ability to replace XA audio with your own. It's only available through the command-line. Take a look at chapter 6.3.2 in the manual. Specially the `-replaceaudio` command. Be aware that the new audio length must be precisely the same length as the original (down to the sample).
Also you'll definitely want to use v1.06. There were several bug fixes to replacing data.

**Comment by AlbertWesker86** [comment]
Thank you so, so much for your insight!! I will do as you say ;D
