### ISSUE TITLE
Replacing audio files not working anymore.

### ISSUE THREAD

**Issue by KRivva** [m35/jpsxdec#85]
Environment
-------------

jPSXdec version: 1.05 - 2.0
Operating system: 
Java runtime environment : 

 PlayStation Game (if applicable)
----------------------------------

Name: 
Region code (e.g. SLUS-1234): 

 Description 
-------------

Hello,
since version 1.05 I'm not able to use the Command-line option for replacing the audio anymore:
`java -jar jpsxdec.jar -x GAME.idx -i 971 -replacexa "title.wav"`

The debug log file contains this information:

```
 jpsxdec.cmdline.CommandLine SEVERE: -replacexa option is missing -xa option
jpsxdec.cmdline.CommandLineException: -replacexa option is missing -xa option
	at jpsxdec.cmdline.Command_Items.handleItem(Command_Items.java:277)
	at jpsxdec.cmdline.Command_Items.access$000(Command_Items.java:68)
	at jpsxdec.cmdline.Command_Items$Command_Item.execute(Command_Items.java:116)
	at jpsxdec.cmdline.CommandLine.main(CommandLine.java:113)
	at jpsxdec.Main.main(Main.java:112)
```

**Comment by m35** [comment]
In v1.05, for replacing audio with a wav file, the command-line `-replacexa` was renamed to `-replaceaudio` (mentioned in the [release notes](https://github.com/m35/jpsxdec/releases/tag/v1.05))
The original `-replacexa` command still exists, but only to copy XA audio directly (a rarely used feature I suspect).

**Comment by KRivva** [comment]
Thank you!
