### ISSUE TITLE
How to extract Tim file for captain tsubasa j get in the tomorrow ps1

### ISSUE THREAD

**Issue by Cruyfford** [m35/jpsxdec#86]
How to extract Tim file like these video 
https://youtu.be/HBvhWDQVj8I?si=hYKf3lA2-J0yGRQI

**Comment by Cruyfford** [comment]
I try not working for me

**Comment by Cruyfford** [comment]
![Uploading IMG_1390.jpeg…]()

**Comment by m35** [comment]
Could you add the debug00.log and more details about the issue you're seeing?

**Comment by Cruyfford** [comment]
the link https://www.mediafire.com/file/0krrhl6ite2q76i/debug00.rar/file

he said We started from the address 0x80190000 (Debugger) where the TIM decompression takes place

and i dont no how to do it

**Comment by m35** [comment]
From what I can tell, the author of that video has written a custom tool that can extract non-standard TIM images from that game, and converts them to standard TIM images. jPSXdec only works for standard TIM images, so won't work for that game unless you use their tool. You'll need to contact that author for help.
