### ISSUE TITLE
FMV's from Road Rash 3D

### ISSUE THREAD

**Issue by Mohsen865** [m35/jpsxdec#9]
>
> It doesn't recognize any FMV from Road Rash 3D.
> 
> [debug0.log](https://github.com/m35/jpsxdec/files/2083446/debug0.log)
>

 Environment
-------------

**jPSXdec** version: v0.99.7 rev3397
Operating system: Win7 64bits
Java runtime environment: Version 8 - Update 44

 PlayStation Game
----------------------------------

Name: **Road Rash 3D**
Region code: I tried both [**SLUS-00524**] and [**SLES-00910**] versions.
![rr3d_ntsc_cd](https://user-images.githubusercontent.com/12261908/42174928-1f33ee04-7e39-11e8-8ddb-d3b5ce2782e7.png)

 Description 
-------------

What happened?: Doesn't recognize any FMV videos, soundtracks, and most of the TIM's / textures.

What was supposed to happen?: To recognize FMV videos, soundtracks, SFX, and more TIM's / textures.

Additional info
-----------------
The soundtracks (which plays during the races) are stored in "ALBUM2.ALB" and "ALBUM.ALB" files, in ADPCM Stereo format plays at 16000Hz and the interleave value is 8192 bytes(?) can be played with "Cube Media Player 2".

The dialogue/monologues, menu music, SFX, and some other sounds are stored in "FENOIZ_E.DAT" and "RASHNZ_E.DAT" files, plays at 8000Hz ~ 16000Hz. (Unknown format but PS Sound plays them / XA maybe).

The FMV video format in this game is still unknown, or at least it's hidden somewhere on the disc! There are at least 62 FMV's in this game though....

**Comment by Mohsen865** [comment]
Update!
-------------

Not sure but I think, I found that which are the FMV files on the game disc! 😅
The files with .WVE extension must be the FMV videos. 

**Example: _EA_LOGO.WVE_**

![wve](https://user-images.githubusercontent.com/12261908/42170783-c20bef76-7e2c-11e8-842d-5ee49ec27c45.png)


## But the file header is not like a MDEC video at all!
![wve_header](https://user-images.githubusercontent.com/12261908/42172389-19b2c746-7e31-11e8-8dfe-69f877d984e4.gif)

**Comment by m35** [comment]
Great job investigating! The game is definitely doing something unique. I'll take a look at it this week and let you know.

**Comment by Mohsen865** [comment]
Thank you very much! ♥

**Comment by m35** [comment]
This game uses completely different ways to encode its FMVs 🙁. There is an upcoming release of jPSXdec in the next month. Unfortunately support for Road Rash 3D FMVs and SFXs won't be added until the release after that (6+ months from now). As for more TIM/textures/images: jPSXdec primary focus really has to be on FMV and SFX simply because anything else is just too much for me (basic TIM support is an exception because it is so common).

**Comment by Mohsen865** [comment]
Good to know. I think I can wait for more 6 months! 😁
Thanks for explanation! ♥
So you found the name of video Codec yet?

I examined the _Road Rash 3D's_ main executable file in _IDA disassembler_... I'm not familiar with those code languages and I don't understand most of them! 😅 But here are _(see the screenshot)_ some mentions about MDEC in the game's exe file. So we have MDEC in this game? Maybe there are normal MDEC but they encrypted the video files, and the game exe decrypt them on the fly? 🤔
![da](https://user-images.githubusercontent.com/12261908/42411613-15da4478-8214-11e8-888a-44bfd2c4c514.png)


If someone who understands the language could check those codes, then we could have uncovered this ~20 years old mystery!

Something else: I noticed that the FMV playback (in _Road Rash 3D, NBA Live 98, and some other EA games_) works in a different way than FMV's in a regular PS1 game!! So on actual console, during the FMV playback if you open the PS1's Disc Cover, it takes a short time (like ~1 second) for the playback to freeze! It seems we have a buffered playback happening here in _Road Rash 3D_; But with a regular FMV _(example: 007 The World Is Not Enough, and almost every PS1 game)_, once you open the Disc Cover, the video playback freezes quickly in no time!

Though if I'm not mistaken, the FMV's visual quality in _Road Rash 3D_ is superior to those other games...

**Comment by m35** [comment]
Shoot me an email at jpsxdec@gmail.com and I can get into more details you might find very interesting.

**Comment by m35** [comment]
Added in this release https://github.com/m35/jpsxdec/releases/tag/v0.99.9

**Comment by Mohsen865** [comment]
> 
> 
> Added in this release https://github.com/m35/jpsxdec/releases/tag/v0.99.9

Thank you for the new release...
Now since the release of this game (21yrs), finally we have an application which plays _Road Rash 3D **FMV**'s_ without needing to run or emulate the game! We can also watch the unused existing FMV's too... 👍

But still something weird is happening to the output frames, on both JPSXDEC and emulation even by using the software renderer on emulator... _The frames width is larger than 320 pixels (321 pixels?)_ 😮
As it is obvious on the following comparison, there's a hidden / cropped column of pixels on both emulator(1st pixels column on the right side of the frames) and the JPSXDEC(1st pixels column on the left) output frames, which proves that the real frames width is larger than 320 pixels!
Note that the original captured screen from the emulator was in native 320x240 pixels with the two top and bottom black bands, before I crop them into 224 pixels, to remove the black bands...
### Here's a comparison GIF between the pictures on JPSXDEC and emulator:
![comparison](https://user-images.githubusercontent.com/12261908/62831853-662f1f00-bc3a-11e9-9021-c160d0e985f5.gif)

Can the resolution be really 321x224? Is it possible to find out how much larger are the original / uncropped frames of the game FMV's?
I'll add more details about this issue in future, if required... 

And I have questions about the FMV's audio track...
What is the audio format? I didn't think that they could be in 22050 Hz! But still they sound like they're even better than 32000 Hz! 😁
Is it possible to add a feature to let the users to save / convert FMV's audio tracks separately just like how we do it for regular STR FMV's of other games?
![audio](https://user-images.githubusercontent.com/12261908/62832377-38e66f00-bc42-11e9-91f2-867cf5cc2182.png)

**Comment by m35** [comment]
I can't think how there could be more than 320 pixels wide. Double checked the source data, and it doesn't have any data beyond 320 pixels wide. Checked the raw VRAM in an emulator, and it also shows only 320 pixels wide (the emulator is showing the image in 16-bit mode, but the data is 24 bit, so it's 1.5x wider). 
![RRSize](https://user-images.githubusercontent.com/409923/62841023-e1eb9480-bc57-11e9-9713-eafa8a40b33a.png)

**Comment by Mohsen865** [comment]
**Ah, I see!
Thanks for the reply.**
But something strange is going on with this game...

Lets add a fame from emulator to a frame from JPSXDEC to see the results...
This is a frame from the intro video (T1.WVE) decoded by JPSXDEC:
![T1.WVE[0]234](https://user-images.githubusercontent.com/12261908/62884641-4f78ed00-bd4c-11e9-9dd8-7846810a7fae.png)

And this is a frame from decoded video by emulator (black bands cropped out):
![DEMO0001 AVI_snapshot_00 11 000_ 2019 08 12_17 23 30](https://user-images.githubusercontent.com/12261908/62885201-784db200-bd4d-11e9-9bd0-646b374a19f1.png)

Here's the output result with 321 pixels width picture:
![DEMO0001 MIX](https://user-images.githubusercontent.com/12261908/62885347-daa6b280-bd4d-11e9-8aef-4603a02c9b63.png)


But I cannot even imagine how a video could be "321" pixels in width!! 😲
Perhaps we'll never know, until we ask from the person who encoded the video files or the game programmers themselves... 😁

And for the final part, I'll add some comparison GIF's here (black bands cropped out):
_Zoom in to see more details_

![DEMO0001-1](https://user-images.githubusercontent.com/12261908/62886270-278b8880-bd50-11e9-890b-8edcdb60d44a.gif)
![DEMO0001-2](https://user-images.githubusercontent.com/12261908/62887602-cfa25100-bd52-11e9-8468-c49e6490dbf6.gif)
![DEMO0001-3](https://user-images.githubusercontent.com/12261908/62886292-37a36800-bd50-11e9-9db8-3f674291928e.gif)
![DEMO0001-4](https://user-images.githubusercontent.com/12261908/62886308-40943980-bd50-11e9-8bb7-76a117b34595.gif)

**Comment by piratesephiroth** [comment]
looks like a problem with the emulator

**Comment by m35** [comment]
@Mohsen865 can you email me about this issue at jpsxdec@gmail.com?

**Comment by Mohsen865** [comment]
> 
> 
> @Mohsen865 can you email me about this issue at [jpsxdec@gmail.com](mailto:jpsxdec@gmail.com)?

**I did!** 👍🙂

**Comment by m35** [comment]
It's been confirmed to be an issue with how the video plugin was saving AVI images.
The extra 1 column of pixels on the left was simply the first 1 column of pixels duplicated, and the right-most 1 column of pixels were cropped off.
